### ISSUE TITLE
Failed to run SpookyJS with command 'casperjs test' with 1.1.0-beta3.

### ISSUE THREAD

**Issue by sennoy** [SpookyJS/SpookyJS#108]
I've latest SpookyJS and CasperJS 1.1.0-beta3.
[Change in casper in 1.1.0-beta3](http://casperjs.readthedocs.org/en/latest/testing.html)
When I tried to use this test I got:

```
CasperError: casper.test property is only available using the `casperjs test` command
CasperError: casper.test property is only available using the `casperjs test` command
  /casper-path/casperjs/n1k0-casperjs-4f105a9/modules/casper.js:179
{ [Error: Child terminated with non-zero exit code 1] details: { code: 1, signal: null } }
```

I tried to override command to run casper like this:

``` javascript
var spooky = new Spooky({
        child: {
            command: "casperjs test"
        },
```

But I'm getting this:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Also, I've tried to launch casperjs directly from node:

```
[~/node-path]$ bin/node 
> spawn = require('child_process').spawn;
[Function]
> var child = spawn('/node-path/bin/casperjs test', [])
undefined
> 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
[~/node-path]$ bin/node
> spawn = require('child_process').spawn;
[Function]
> var child = spawn('/node-path/bin/casperjs', ['test'])
undefined
> child
{ domain: null,
  _events: {},
  _maxListeners: 10,
  _closesNeeded: 3,
  _closesGot: 3,

```

As you can see calling spawn with '/path/to/casperjs test' failing, looks like it interprets it like another process to run.. I'm not very good in this terminology.
Here is what I have for now:

```
[~/node-path]$ bin/casperjs test /node-path/node_modules/spooky/lib/bootstrap.js --command=casperjs --port=8081 --spooky_lib=/node-path/node_modules/spooky/lib/../ --transport=stdio
Test file: /node-path/node_modules/spooky/lib/bootstrap.js
{"jsonrpc":"2.0","method":"emit","params":["ready"]}
```

I'm able to launch it manually, but when I'm trying to modify args variable [here](https://github.com/WaterfallEngineering/SpookyJS/blob/master/lib/spooky.js#L190):
it gives me following:

```
[~/node-path]$ ./node testRunner.js
casperjs // output from console.log(options.command);
{} // output from console.log(options.spawnOptions);
[ 'test /node-path/node_modules/spooky/lib/bootstrap.js',
  '--command=casperjs',
  '--spawnOptions=[object Object]',
  '--port=8081',
  '--spooky_lib=/node-path/spooky/lib/../',
  '--transport=stdio' ] // output from console.log(args);

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Child terminated with non-zero exit code 1
    at Spooky.<anonymous> (/node-path/node_modules/spooky/lib/spooky.js:185:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)
```

as you can see I've tried to modify args here to launch casperjs in test mode.
I've also tried to add 'test' as separate item:
[ 'test', ...
but that didn't worked too.

**Comment by jonasflesch** [comment]
I think this is very important :(

**Comment by victorguerra95** [comment]
Worked for me:

https://github.com/SpookyJS/SpookyJS/issues/114
