### ISSUE TITLE
Error while running example.js

### ISSUE THREAD

**Issue by vcvetkovs** [SpookyJS/SpookyJS#209]
Installed spooky, casperjs and phantomjs via npm and when running example.js getting error
`{ [Error: Child terminated with non-zero exit code 1] details: { code: 1, signal: null } }`. Any suggestions how to solve? (Tried also to install spooky dependencies manually via cd node_modules/spooky and then npm install)

My code: http://pastebin.com/TrMghg4D

But when i am trying to launch from command line `casperjs d:\Docs\WebStorm\Crawler\node_modules\spooky\lib/bootstrap.js --command=casperjs.cmd --transport=http --port=8081 --spooky_lib=d:\Docs\WebStorm\Crawler\node_modules\spooky\lib/../ --spawnOptions=[object Object]`, all works fine - it outputs: `{"jsonrpc":"2.0","method":"emit","params":["ready"]}`

**Comment by vcvetkovs** [comment]
Found solution, maybe it will helps for somebody, as command i used path to casperjs exe file
 `new Spooky({
    child: {
        command: "node_modules/casperjs/bin/casperjs.exe"
    }
});`

if there will be error that phantomjs not found, this line of code will resolve that problem 
`process.env.PHANTOMJS_EXECUTABLE = 'node_modules/phantomjs/lib/phantom/bin/phantomjs.exe';`

**Comment by HugoPoi** [comment]
After installing `casperjs phantomjs-prebuilt spooky`
In the documentation `node node_modules/spooky/examples/hello.js` throw

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

Enhancements
1. Spooky need to throw error details about missing binaries dependencies.
2. Implement looking into node_modules for already installed modules.

**Comment by lokisama** [comment]
Whats your solution? I met the error too 
Error: spawn ENOENT

**Comment by HugoPoi** [comment]
You must provide the casper path as indicate in @vcvetkovs comment https://github.com/SpookyJS/SpookyJS/issues/209#issuecomment-232481284
