### ISSUE TITLE
mocha cann't  pass the bootstrap.js

### ISSUE THREAD

**Issue by zhouweihua** [SpookyJS/SpookyJS#215]
D:\testWork\SpookyJS-master>mocha ./tests/test/bootstrap.js

  the PhantomJS bootstrap script
    1) hooks phantom.onError to emit an error event and exit non-zero
    2) crashes if passed an unknown transport

  0 passing (21ms)
  2 failing

  1) the PhantomJS bootstrap script hooks phantom.onError to emit an error event and exit non-zero:
     Uncaught Error: spawn casperjs.bat ENOENT
      at exports._errnoException (util.js:1022:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:359:16)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) the PhantomJS bootstrap script crashes if passed an unknown transport:
     Uncaught Error: spawn casperjs.bat ENOENT
      at exports._errnoException (util.js:1022:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:359:16)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by zhouweihua** [comment]
i have run the program in the centos 7
