### ISSUE TITLE
Phantom's cookiesEnabled property

### ISSUE THREAD

**Issue by rodyhaddad** [SpookyJS/SpookyJS#33]
How is it possible to set Phantom's `cookiesEnabled` property to true while using SpookyJS?
Also, how do I pass the `--cookies-file` option for Casper/Phantom?

**Comment by Crispy1975** [comment]
Quite an old issue but found it via Google today as I require the use of cookies with PhantomJS through Spooky... here is the result...

```
			cookies-file: process.cwd() + 'cookiesFile',
			       ^

SyntaxError: Unexpected token -
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/crispy/test/index.js:187:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

```

Here is the child object used when instantiating Sppoky...

```
	child: {
				'cookies-file': process.cwd() + 'cookiesFile',
				transport: 'http',
		        proxy: '127.0.0.1:8118'
			}
```

Any ideas would be great. Thanks.
