### ISSUE TITLE
Example hello.js can't run [Window]

### ISSUE THREAD

**Issue by royalgarter** [SpookyJS/SpookyJS#71]
Hi all,

I tried to test Spooky on window but can't start it (installed phantom, casper and added them to PATH, installed spooky via npm)

Here what I got:

e:\workspace\trunk\labs\node_ws>node node_modules/spooky/examples/hello.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Anyone can help?

**Comment by mduqueoviedo** [comment]
I had the same problem with OSX and I found that reinstalling casperjs with this option:

$ npm install -g casperjs
(The -g flag makes the casperjs executable available system-wide.)

For some reason it wasn't available, I probably forgot to add the -g

**Comment by rendermouse** [comment]
On Windows, make sure you:
* Have the LATEST (beta) CasperJS binaries installed. I had an older version and it threw the ENOENT error due to a version conflict with a new version of Phantom.
* Have CasperJS and Phantom locations set in your Windows path
* Create a *new* command line from Start>Run>cmd after editing your path before you run your Node script. If you edit your path and then just do "command line here" in your project folder, it uses the OLD path until you logoff/restart.

**Comment by brycepj** [comment]
Re-installing casperjs globally worked for me.

`npm install -g casperjs`

Thanks @mduqueoviedo

**Comment by yeralin** [comment]
I need to install casperjs localy, but I'm getting spawn casperjs ENOENT.

I tried to just put casperjs directory into Spooky's node_modules, it didn't work.

**Comment by pedro93** [comment]
Please refer to issue #131, see if the hotfix mentioned laggingreflex works for you

**Comment by NikIvan** [comment]
Thanks @rendermouse. Installed beta version of casperjs and it fixed my problem.

**Comment by smalltalk-josh** [comment]
I finally got it working, and I wanted to share my steps to get it working.

Note: the install is using casperjs as a module. I did NOT globally install since this is deployed onto servers

OS: Windows (dev) / linux (prod)
Installed:
* phantomjs-prebuilt: ^2.1.14 - `npm i phantomjs-prebuilt -S`
* casperjs: ^1.1.3 - `npm i casperjs -S`
* spooky: ^0.2.5 - `npm i spooky -S`
* tiny-jsonrpc: - `npm i tiny-jsonrpc -S`
* underscore: - `npm i underscore -S`

There are two issues:
1. path to casperjs and phantomjs-prebuilt
2. finding casperjs file

Paths Issue

```javascript
const
  path = require('path'),
  _ = require('underscore')
;
var
  // close env to pass to spawn
  env = _.clone(process.env),
  // get the PATH - in my local Windows, it was Path
  envPath = env.PATH || env.Path,
  // get path to node_modules folder where casperjs and
  // phantomjs-prebuilt are installed
  // this will be different for you
  binDir = path.join(__dirname, './../../node_modules/.bin'),
  Spooky = require('spooky')
;
// update the path in the cloned env
env.PATH = env.Path = `${envPath};${binDir}`;
```
The path is now updated in the cloned env object. 

```javascript
var spooky = new Spooky({
  child: {
    // spooky is trying to call casperjs.bat for windows
    // .bat doesn't work, so call the update .cmd file
    // this fixes issue 2 with the file
    command: /^win/.test(process.platform) ? 'casperjs.cmd' : 'casperjs',
    transport: 'http' ,
    spawnOptions: {
      // set the env using cloned version
      // this fixes issue 1 with the path
      env: env
    }
  },
  ... 
```

Thanks to:
* Issue 1: https://github.com/SpookyJS/SpookyJS/issues/206#issuecomment-223816050
* Issue 2: https://github.com/SpookyJS/SpookyJS/issues/114#issuecomment-59407132

**Comment by elimence** [comment]
@smalltalk-josh followed your steps on OSX but then I'm getting this:
`message: 'undefined is not a constructor (evaluating \'require(\'webpage\').create()\')' }`
any ideas what this is about?
Thanks

**Comment by smalltalk-josh** [comment]
@elimence I'm not sure about that error. It appears to be unrelated to the `Error: spawn ENOENT`

The error I was having would not even start the process. You appear to be having an issue with a different command: `require('webpage').create()`

**Comment by victorguerra95** [comment]
Worked for me:

https://github.com/SpookyJS/SpookyJS/issues/114
