### ISSUE TITLE
Impossible run Spooky:  Child terminated with non-zero exit code 1

### ISSUE THREAD

**Issue by CodersBrothers** [SpookyJS/SpookyJS#74]
I'm using Debian GNU/Linux 7

Versions STACK:

``` code
Node: v0.10.15
PhantomJS: 1.9.2
CasperJS: 1.1.0-DEV
```

Content of app.js: 

``` javascript

try {
    var Spooky = require('spooky');
} catch (e) {
    console.log("ERROR");
    var Spooky = require('../lib/spooky');
}


var defaults = {
    transport: {
        http: {
            host: 'localhost'
        }
    },
    child: {
        command: 'casperjs',
        port: 8081,
        script: './node_modules/spooky/lib/bootstrap.js',
        spooky_lib: './node_modules/spooky/',
        transport: 'http',
        bufferSize: 16 * 1024 // 16KB
    },
    casper: {
        verbose: true,
        logLevel: 'debug',
        clientScripts:  [
            'lib/jquery.min.js',
        ]
    }
};
var spooky = new Spooky(defaults, function (err) {


    if (err) {
        var e = new Error('Failed to initialize SpookyJS');
        e.details = err;
        throw e;
    }

    spooky.start('https://www.twitter.com', function(){

        this.capture('./captures/twitter.png');

    });

    spooky.thenEvaluate(function () {

        $("#signin-email").val(":D");

    });

    spooky.then(function() {

        this.capture('./captures/twitter2.png');

    });

    spooky.run();

});
```

In shell:

``` code
node app.js
```

ERROR:

``` code
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Child terminated with non-zero exit code 1
    at Spooky.<anonymous> (/home/leif/proyectos/testSpooky/node_modules/spooky/lib/spooky.js:177:17)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)

```

I make a console log like https://github.com/WaterfallEngineering/SpookyJS/issues/59#issuecomment-19059810

``` code
casperjs ./node_modules/spooky/lib/bootstrap.js --command=casperjs --port=8081 --spooky_lib=./node_modules/spooky/lib/ --transport=http --bufferSize=16384
```

**Comment by joseym** [comment]
I'm new to this whole `spookyjs` business, and I feel like I'm to blame for this error since this ticket is closed and __> 2__ years old.

~~~shell
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Child terminated with non-zero exit code 1
    at Spooky.<anonymous> (/app/node_modules/spooky/lib/spooky.js:210:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
~~~

__PhantomJS__
> phantomjs --version
> 1.9.8

__CasperJS__
> casperjs --version
> 1.1.0-beta3

__Heroku__
_buildpacks_
> 1. https://github.com/leesei/heroku-buildpack-casperjs.git
> 2. heroku/nodejs

**Comment by stenrap** [comment]
You're not alone, @joseym. I'm seeing the exact same problem.

**Comment by pedro93** [comment]
@joseym and @stenrap Can you please verify if both dependencies are installed globally? I've also had a similar problem but seemed to be fixed when I got both PhantomJS and CasperJS installed and executable in a global namespace

**Comment by danielkalen** [comment]
To see what casperJS is saying, I passed the following object to child.spawnOptions: `{stdio: 'inherit'}` which has the casperJS child process use the executing script's stdio. Here is the output I got (replaced my home dir with ######)
```
{
	"jsonrpc":"2.0",
	"method":"emit",
	"params":[
		"error",
		"Error: Cannot find module '/######/node_modules/spooky/lib/../node_modules/tiny-jsonrpc/lib/tiny-jsonrpc'",
		[
			{"file":"phantomjs://bootstrap.js","line":289,"function":""},
			{"file":"phantomjs://bootstrap.js","line":254,"function":"require"},
			{"file":"/######/node_modules/spooky/lib/bootstrap/http-server.js","line":6,"function":""},
			{"file":"/######/node_modules/spooky/lib/bootstrap/http-server.js","line":65,"function":""}
		]
	]
}
```

And this reveals the source of the problem... The script tries to access the `tiny-jsonrpc` directory/module that's located in spooky's parent `node_modules` directory via `../` but falls short as it needs to traverse an additional directory upwards (`../../node_modules/`).
